name: toy_manager
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 

  flutter_screenutil: ^5.9.0
  pull_to_refresh: ^2.0.0
  package_info_plus: ^8.0.0
  flutter_inappwebview: ^6.0.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  share_plus: ^9.0.0
  dio: ^5.4.3+1
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_timezone: ^1.0.8
  faker: ^2.1.0
  bot_toast: ^4.1.3
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  flutter_launcher_icons: ^0.13.1

  flutter_localizations:
    sdk: flutter
  flutter: 
    sdk: flutter

flutter_launcher_icons:
  image_path: "assets/images/start.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/start.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/


flutter_assets:
  assets_path: assets/images/
  output_path: lib/assets
